### ISSUE TITLE
请求友链添加

### ISSUE THREAD

**Issue by aFlyBird0** [lewky/lewky.github.io#3]
你好，请求添加友链。我的 [博客友链](https://blog.aflybird.cn/friends/) 位置。

name="飞鸟记"
url="https://blog.aflybird.cn/"
logo="https://avatars.githubusercontent.com/u/36830265"
word="记录「技术」与「温度」"

**Comment by lewky** [comment]
已添加，另外贵站中关于我的友链有些问题，请帮忙改用下面的网站和图标链接：
```
url="https://lewky.cn"
logo="https://lewky.cn/images/avatar.jpg"
```
